extends Node

signal choosing_action_state_entered
signal choosing_action_queue_state_entered
signal choosing_skill_state_entered
signal choosing_enemy_state_entered
signal is_battling_state_entered

